name: CI Retrain + Docker (MLflow Project)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn scipy numpy matplotlib

      - name: Run MLflow Project (re-train)
        working-directory: MLProject
        run: |
          mlflow run . --env-manager local -P run_name="ci_retrain_${GITHUB_SHA::7}"

      - name: Upload training artifacts (Skilled)
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: MLProject/artifacts_out/

      - name: Locate latest logged model
        id: modelpath
        working-directory: MLProject
        run: |
          MODEL_DIR=$(ls -td mlruns/*/*/artifacts/model | head -n 1)
          echo "model_dir=$MODEL_DIR" >> $GITHUB_OUTPUT
          echo "Found model: $MODEL_DIR"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with mlflow models build-docker (Advance)
        working-directory: MLProject
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/adult-income-mlflow"
          if [ -n "${{ secrets.IMAGE_REPO }}" ]; then
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_REPO }}"
          fi
          mlflow models build-docker -m "${{ steps.modelpath.outputs.model_dir }}" -n "$IMAGE_NAME:latest"

      - name: Push Docker image (Advance)
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/adult-income-mlflow"
          if [ -n "${{ secrets.IMAGE_REPO }}" ]; then
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_REPO }}"
          fi
          docker push "$IMAGE_NAME:latest"
