name: CI Retrain + Docker (MLflow Project)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    env:
      # DagsHub / MLflow Online Tracking
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_EXPERIMENT_NAME: ${{ secrets.MLFLOW_EXPERIMENT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy scipy matplotlib joblib

      - name: Run MLflow Project (re-train)
        run: |
          mlflow run MLProject --env-manager=local -P run_name="ci_retrain_${GITHUB_SHA::7}"

      - name: Read RUN_ID
        id: runinfo
        run: |
          RUN_ID=$(cat MLProject/artifacts_out/run_id.txt)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "RUN_ID is $RUN_ID"

      - name: Upload training artifacts (Skilled)
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: MLProject/artifacts_out/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with MLflow (Advance)
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/adult-income-mlflow"
          if [ -n "${{ secrets.IMAGE_REPO }}" ]; then
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_REPO }}"
          fi

          MODEL_URI="runs:/${{ steps.runinfo.outputs.run_id }}/model"
          echo "Building image from model uri: $MODEL_URI"
          mlflow models build-docker -m "$MODEL_URI" -n "$IMAGE_NAME:latest"

      - name: Push Docker image (Advance)
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/adult-income-mlflow"
          if [ -n "${{ secrets.IMAGE_REPO }}" ]; then
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_REPO }}"
          fi
          docker push "$IMAGE_NAME:latest"
